### ISSUE TITLE
Strange field label

### ISSUE THREAD

**Issue by gmclelland** [wanze/TemplateEngineTwig#14]
I'm not sure why, but I'm seeing a weird label when I visit the module's configuration page.
See this image:
![twig](https://user-images.githubusercontent.com/40570/39212899-b05b702c-47d5-11e8-9efb-f12c4e6cd69c.jpg)

**Comment by gmclelland** [comment]
Strange... On another fresh install site, it shows correctly.

**Comment by gmclelland** [comment]
This is weird.  No matter what I do, I can't get it show correctly.  I've tried reinstalling a fresh copy and deleting this module from the TemplateCompiler's caches. I've also tried uninstalling and reinstalling this module and TemplateEngineFactory.

For some reason this module is getting compiled with Processwire's Compiler and I think the code generated is causing the problem?

But that seems weird that it would work on one test site and not the other?

**Comment by gmclelland** [comment]
Strange.  I just upgraded another local site.  It was working fine at TemplateEngineTwig 1.04, but after the upgrade to TemplateEngineTwig 1.10 I'm seeing the same weird labels in the image above.

**Comment by gmclelland** [comment]
With some help from Robin at https://processwire.com/talk/topic/19514-modules-page-gettting-compiled/, I was able to resolve this by adding a php comment in the module file.  That forced the module to recompile and it no longer shows incorrectly.

He thinks it might be related to this core issue:
https://github.com/processwire/processwire-issues/issues/98

**Comment by gmclelland** [comment]
I thought this was fixed, but I'm still seeing the issue on one site.  I still think it may be Processwire's File Compiler that is causing the issue?   We probably just need to wait and follow this issue https://github.com/processwire/processwire-issues/issues/98.

**Comment by wanze** [comment]
Yep this is 100% related to the file compiler of ProcessWire. I am closing this one since this is a core issue.
