### ISSUE TITLE
Doesn't work with Hanna Code?

### ISSUE THREAD

**Issue by binarious** [wanze/TemplateEngineTwig#16]
I tried to combine the twig template engine with Hanna Code (http://modules.processwire.com/modules/process-hanna-code/), but it doesn't seem to work. The tag doesn't get replaced with the actual code. 

Template:
```html
<p>{{ page.body|raw }}</p>
```

Any ideas?

**Comment by wanze** [comment]
The template engine factory only affects the rendering of pages, not hanna tags. You would need a custom module that hooks into the rendering process of these tags, then use TemplateEngineTwig to render the twig syntax.

**Comment by binarious** [comment]
Thanks, do you have a starting point (documentation or examples) for me?
