### ISSUE TITLE
Compatibility with Version Control module

### ISSUE THREAD

**Issue by lesaff** [wanze/TemplateEngineTwig#17]
We use Twig templates exclusively for all of our PW sites. I noticed that on [Version Control Module](https://github.com/teppokoivula/VersionControl) preview, it threw exception error (see below) whenever TemplateFactory and TemplateTwig is being used. 

Thx

<img width="729" alt="screen shot 2018-09-12 at 1 50 14 pm" src="https://user-images.githubusercontent.com/1151181/45440556-f6fc2400-b692-11e8-953c-fcfa1e88cd50.png">

**Comment by wanze** [comment]
Unfortunately I do not know the Version Control Module myself. It seems like this module uses another process of rendering pages, so this problem most likely cannot be fixed within this module. It should be the other way around ;-)

However, you can fix the exception being thrown. The `if` statement will always be true, as the class exists also if `$view` is `null. Instead, check if the `$view` variable is not `null`. This will fix the exception, but you will not get the rendered markup from Twig.

**Comment by lesaff** [comment]
@wanze, Thanks for your insights.

Yes, for now this will suppress the exception error until your new version comes out.

```
if (class_exists("TemplateEngineTwig", false) && $view) {
    $view->setArray([

    ]);
}
```
Merry Christmas! 🎄

**Comment by wanze** [comment]
@lesaff Version 2.0 of the module is now released. It requires TemplateEngineFactory 2.0, which might require some manual update steps. If you find time to update or if you can test it out in another project, let me know if this issue has been fixed. :)

Cheers

**Comment by lesaff** [comment]
@wanze Will do. I'll report back with my notes.

**Comment by lesaff** [comment]
Exception error is now gone but it's just displaying blank page. I guess I need to find a way to render my twig layout on the Version Control module view as well.

**Comment by wanze** [comment]
@lesaff The blank page only appears in the context of the Version Control module?

**Comment by wanze** [comment]
@lesaff Any progress on this issue? Version `2.x` of TemplateEngineFactory should output the markup from the template engine when calling `Page::render()`. So it should theoretically work, but it depends on how the version control module handles the rendering. I am closing since I think there's not much the module can do. Feel free to reopen :)

Cheers
