### ISSUE TITLE
TemplateEngineTwig does not appear on modules list after installation

### ISSUE THREAD

**Issue by lesaff** [wanze/TemplateEngineTwig#20]
Installed via composer `composer require wanze/template-engine-twig:^2.0`

Refreshed the modules page and only seeing 
`Template Engine Factory` and `Template Engine ProcessWire` but not `TemplateEngineTwig`.

Looking at the modules folder, I can see that module was added.

**Comment by wanze** [comment]
Try clearing the compiled cache and refreshing the modules once again, I remember to had a similar problem. You might also need to re-add Twig as active engine in the module config settings.

**Comment by lesaff** [comment]
I had to do that several times but it finally shows up. Thx
