### ISSUE TITLE
Can't use engine( please help

### ISSUE THREAD

**Issue by khudia** [wanze/TemplateEngineTwig#22]
Fatal Error: Uncaught Error: Class 'Twig_Loader_Filesystem' not found in /Users/Regesh/Sites/localhost/site/modules/TemplateEngineTwig/src/TemplateEngineTwig.php:51
if select smart - the same(
thanks

**Comment by wanze** [comment]
Hi @khudia 

Which version of the TemplateEngineFactory and TemplateEngineTwig are you using? If you use `v2`, you must install the module with Composer to get the Twig dependencies. The error indicates that Twig is not getting autoloaded correctly.

Run the following command in your ProcessWire root directory:

```
composer require wanze/template-engine-twig:^2.0
```

This will add the latest version of TemplateEngineTwig and TemplateEngineFactory (and Twig). After that, you need to install/configure both modules in ProcessWire. Does that help?

Cheers

**Comment by khudia** [comment]
I'll check! thanks! Started project with version 1

**Comment by wanze** [comment]
I'm closing this issue, please re-open if the described problem still occurs.
