### ISSUE TITLE
update for compatibility with PHP 7.4

### ISSUE THREAD

**Issue by VincentVanWijk** [wanze/TemplateEngineTwig#24]
Hi,

can this module be updated to be compatible with PHP 7.4?
There are a lot of warnings of deprecated when using this version

**Comment by wanze** [comment]
Hi @VincentVanWijk 

Which version of the module are you using and what kind of warnings to you get? If you're still on `v1.x` you should update to version `2.x`. Installation for the `2.x` version is only possible with Composer.

**Comment by VincentVanWijk** [comment]
hi @wanze ,

we are using the 1.1 version of the module, we will try to update, and let you know if we get any errors.
