### ISSUE TITLE
Fix deprecation warnings for PHP 8.2

### ISSUE THREAD

**Issue by hiboudev** [wanze/TemplateEngineTwig#26]
Warning in PW admin when installing module in PHP 8.1:

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in site\modules\TemplateEngineTwig\src\TemplateEngineTwig.php on line 128

**Comment by wanze** [comment]
Hi @hiboudev 
Thanks for the info, I think you mean PHP `8.2`. Could you send a pull request?

**Comment by hiboudev** [comment]
Yes it's 8.2. Pull request created: https://github.com/wanze/TemplateEngineTwig/pull/29

**Comment by wanze** [comment]
Thanks, merged and will create a new release.
