### ISSUE TITLE
Can not access ID of a FieldtypeOptions option

### ISSUE THREAD

**Issue by hiboudev** [wanze/TemplateEngineTwig#28]
I'm using the default PW "Select Options" component and when trying to get ID of the option from a Twig, it throws an error:

```
Fatal Error: Uncaught ArgumentCountError: Too few arguments to function SelectableOptionArray::hasID(), 0 passed in E:\path\vendor\twig\twig\src\Extension\CoreExtension.php on line 1635 and exactly 1 expected in E:\path\wire\modules\Fieldtype\FieldtypeOptions\SelectableOptionArray.php:262

#0 E:\path\vendor\twig\twig\src\Extension\CoreExtension.php(1635): SelectableOptionArray->hasID()
#1 E:\path\site\assets\cache\TemplateEngineTwig_compile\72\7271faee4ef038b8f49fabbd4afa01b2.php(137): twig_get_attribute(Object(Twig\Environment), Object(Twig\Source), Object(SelectableOptionArray), 'id', Array, 'any', false, false, false, 53)
```

Code:
`{{ user.membershipStatus.id }}`

The same code in PHP works fine:
`$user->membershipStatus->id`

**Comment by wanze** [comment]
Twig has some issues calling dynamic properties using PHP's [__get](https://www.php.net/manual/en/language.oop5.overloading.php#object.get) which is used quite a lot in ProcessWire. Try accessing it explicitly, something like `{{ user.get('membershipStatus').id }}` or even `{{ user.get('membershipStatus').get('id') }}`. Does that help?

**Comment by hiboudev** [comment]
Hello @wanze 

I faced the same kind of issue today.

At first I thought is was a PW error, so I reported [this issue](https://github.com/processwire/processwire-issues/issues/1827).

I have a Profields Table containing a Text field. If the field is empty I get an error from Twig, if the field is filled it works.
`{{ penalty.reason }}`

I tried to follow your instructions and it works:
`{{ penalty.get('reason') }}`

This is strange, because it seems it doesn't happen with an Integer field. It looks like we need to use get() only in some cases, depending on the field type and if it has content. I'm afraid to get some random errors in the future if I don't use get() everywhere.
I don't know if there's something you can do on your side to make this more consistent, or if it's outside your range in Twig core code?

**Comment by wanze** [comment]
Hi @hiboudev
As far as I know, there is no way to configure Twig to handle magic getters differently. So I think the best strategy is to always access values via the `WireData::get()` method if your object extends `WireData`.
